
services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: programwithgio-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:latest
    container_name: programwithgio-nginx
    restart: always
    ports:
      - 8080:81
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
      